---
title: "UTM_Planas"
author: "JoseOro"
date: "2024-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Librerías a utilizar

```{r}

library(shiny)
library(sf)
library(geosphere)
library(dplyr)
library(DT)

```
## Función de Cálculo "UTMtoPlanas

```{r cars}
# modules/utmToPlanas.R

# Función de transformación UTM a Planas
funcion_UTM_planas <- function(p, crs_input) {
  a <- 6378137.00
  b <- 6356752.314
  e2 <- 0.00669438
  et2 <- 0.006739497
  c <- 6399593.626
  k_0 <- 0.9996
  
  h <- st_as_sf(p, coords = c("E", "N"), crs = crs_input)
  q <- st_transform(h, crs = 4326)
  m <- st_coordinates(q)
  
  k_esc <- matrix(nrow = nrow(m), ncol = 1)
  k_ele <- matrix(nrow = nrow(m), ncol = 1)
  k_com <- matrix(nrow = nrow(m), ncol = 1)
  azimut_grad <- matrix(nrow = nrow(m), ncol = 1)
  azimut_rad <- matrix(nrow = nrow(m), ncol = 1)
  distance_UTM <- matrix(nrow = nrow(m), ncol = 1)
  distance_top <- matrix(nrow = nrow(m), ncol = 1)
  e_top <- matrix(nrow = nrow(m), ncol = 1)
  n_top <- matrix(nrow = nrow(m), ncol = 1)
  
  for (i in 1:nrow(m)) {
    x <- 500000 - p[i, 1]
    q <- 0.000001 * x
    
    n_k <- a / ((1 - e2 * (sin(m[i, 2] * pi / 180))^2)^(1/2))
    p_k <- (10^(12)) * ((1 + et2 * (cos(m[i, 2] * pi / 180))^2) / (2 * n_k^2 * k_0^2))
    k_esc[i, 1] <- k_0 * (1 + p_k * q^2 + 0.00003 * q^4)
    k_ele[i, 1] <- (a * (1 - e2)) / (a * (1 - e2) + p[i, 3] * (1 - e2 * (sin(m[i, 2] * pi / 180))^2)^(3/2))
    k_com[i, 1] <- k_esc[i, 1] * k_ele[i, 1]
    if (i == 1) {
      azimut_grad[i, 1] <- 90
    } else {
      azimut_grad[i, 1] <- st_azimuth(h[1, 1], h[i, 1])
    }
    azimut_rad[i, 1] <- azimut_grad[i, 1] * pi / 180
    distance_UTM[i, 1] <- st_distance(h)[i, 1]
    distance_top[i, 1] <- distance_UTM[i, 1] / mean(c(k_com[i, 1], k_com[1, 1]))
    e_top[i, 1] <- p[1, 1] + distance_top[i, 1] * sin(azimut_rad[i, 1])
    n_top[i, 1] <- p[1, 2] + distance_top[i, 1] * cos(azimut_rad[i, 1])
  }
  
  datos <- data.frame(
    "Lat" = m[, 2], "Long" = m[, 1], 
    "k_esc" = k_esc, "K_ele" = k_ele, 
    "K_com" = k_com, "dist_UTM" = distance_UTM, 
    "Acimut_rad" = azimut_rad, "acimut_grad" = azimut_grad, 
    "dist_top" = distance_top, "E_top" = e_top, "N_top" = n_top
  )
  return(datos)
}

```

## Ruta del archivo CSV
Cargando Datos:

```{r}
archivo <- file.choose()
datos <- read.csv(archivo, header = TRUE)
# Validar si las columnas requeridas existen
columnas_requeridas <- c("PUNTO", "NORTE", "ESTE", "h")
if (!all(columnas_requeridas %in% colnames(datos))) {
  stop("El archivo no contiene las columnas requeridas: PUNTO, NORTE, ESTE, h")
}
head(datos)
```
## Especificando parámetros de entrada (Zona y  Hemisferio)
```{r}
zona_utm <- 19    # Ejemplo: Zona UTM 19
hemisferio <- "S" # Ejemplo: Hemisferio Sur
```
# Definiendo EPSG según la Zona y Hemisferio
```{r}
    if (hemisferio == "N") {
    crs_utm <- paste0("EPSG:", 32600 + zona_utm)  # Hemisferio Norte
  } else if (hemisferio == "S") {
    crs_utm <- paste0("EPSG:", 32700 + zona_utm)  # Hemisferio Sur
  } else {
    stop("El hemisferio debe ser 'N' (Norte) o 'S' (Sur).")
  }
```
# Transformando a un objeto "sf"

```{r}
  # Convertir a un objeto 'sf'
  puntos_utm <- st_as_sf(datos, coords = c("ESTE", "NORTE"), crs = crs_utm)
```

# Transformando a WGS84 (EPSG:4326)
```{r}
puntos_wgs84 <- st_transform(puntos_utm, crs = 4326)
head(puntos_wgs84)
```
# Extrayendo Coordenadas

```{r}
coords <- st_coordinates(puntos_wgs84)
nrow(coords)
```


